= CalConnect Standard: JSCalendar and related documents

This work item belongs to CalConnect TC API.

image:https://github.com/CalConnect/cc-jscalendar/workflows/generate/badge.svg["Build Status", link="https://github.com/CalConnect/cc-jscalendar/actions?workflow=generate"]

This document is available in its rendered forms here:

* https://calconnect.github.io/cc-jscalendar/[CalConnect: JSCalendar and related documents (HTML)]

== General

This document specifies the JSCalendar and related documents.

This specification defines a JSON representation of calendar data
that can be used for storage and data exchange in a calendaring and
scheduling environment.  It aims to be an alternative to the widely
deployed iCalendar data format and to be unambiguous, extendable and
simple to process.

The latest RFC draft version of this document is located at
[draft-ietf-calext-jscalendar](https://datatracker.ietf.org/doc/draft-ietf-calext-jscalendar/).

This repository contains the following documents:

JSCalendar 2020::
** CalConnect CC 51015:2020
** IETF draft-ietf-calext-jscalendar-32

JSCalendar 2022::
** CalConnect CC 51015:2022
** IETF draft-ietf-calext-jscalendarbis-01

JSCalendar: Converting from and to iCalendar::
** CalConnect CC 51026:2022
** IETF draft-ietf-calext-jscalendar-icalendar-07

iCalendar: Representing fractional seconds in iCalendar::
** CalConnect CC 51024:2021
** IETF draft-ietf-calext-icalendar-fractional-time-03

iCalendar Format Extension for JSCalendar::
** CalConnect CC 51025:2022
** IETF draft-ietf-calext-icalendar-jscalendar-extensions-00


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/cc-jscalendar/
----


== Installing build tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate --agree-to-terms
----


== Building the document

[source,sh]
----
metanorma site generate --agree-to-terms
----

The generated documents are accessible under `_site/`.


== Iterating the document

[source,sh]
----
metanorma site generate --agree-to-terms
open _site/index.html
----


// == IETF: Checking against idnits

// https://tools.ietf.org/tools/idnits/[idnits] is the RFC checking tool prior to
// submissions.

// [source,sh]
// ----
// idnits draft-calconnect-vobject-vformat.nits
// ----


== License

Copyright its respective authors and CalConnect.
