[[new-icalendar-parameters]]
== New iCalendar parameters

[[fractional-parameter]]
=== FRACTIONAL parameter

Parameter name:: FRACTIONAL

Purpose:: This parameter is used to contain a value with fractional seconds for time values
and durations.

Description:: This parameter MAY be specified on properties of type DATE-TIME or DURATION. It
MUST be a valid iCalendar DATE-TIME or DURATION value with the addition of fractional
seconds. The value MUST NOT be negative for durations but MAY be negative for alarm triggers.
+
--
Applications receiving a property with a FRACTIONAL parameter MUST ensure its value is
consistent with the value of the property. The property value must match:

* a positive FRACTIONAL value rounded up to the next non-fractional second or
* a negative FRACTIONAL value rounded down the next non-fractional second

If the values do not match the the application MUST assume that the property value has been
updated by an application that is unaware of the FRACTIONAL parameter. The parameter should
be ignored in this case.
--
Format Definition:: This parameter is defined by the following notation:
+
[source%unnumbered]
----
fractional-param = DATE-TIME or DURATION
----

Example::
+
[source%unnumbered]
----
DTSTART;FRACTIONAL=20190605T133015.03:20190605T133015
----
