[[translate-icalendar-components]]
== Translating iCalendar components to JSCalendar

This section is an alphabetic list of <<RFC5545>> components and how they are mapped to
JSCalendar.

At present VFREEBUSY and VJOURNAL are not mapped in JSCalendar.

=== VALARM

An <<RFC5545>> VALARM component is mapped to a member of a JSCalendar "alerts" object with a
type of "Alert" and a small id.

[source%unnumbered]
----
BEGIN: VEVENT
...
BEGIN: VALARM
...
END: VALARM
BEGIN: VALARM
...
END: VALARM
END: VEVENT

maps to

{
  "@type": "Event",
  ...
  "alerts": {
    "1": {
      "@type": "Alert",
      ...
    },
    "2": {
      "@type": "Alert",
      ...
    }
  }
}
----

The <<RFC5545>> VALARM has a number of problems which are not carried over into JSCalendar.
Clients tend to choose how, and in some cases when to notify the user.

For example, if the user has a smart-watch they may get tapped on the wrist. The method of
notification may depend on which device is being used and the context, for example a meeting
or driving.

Also, many clients are taking into consideration the travel time and notifying the user
earlier if it seems necessary.

Specifying that a client should send emails to all attendees is both annoying and dangerous.
Attendees have their own preferences for how and when they should be notified.

Accordingly, the specification only allows for "display" and "email" actions and - other than
specifying when - does not allow much else. Clients and/or servers will generally use the
associated event or task title as identification. User preferences generally indicate what
actions they prefer.

Any ATTENDEE properties in the VALARM MUST be ignored.

An <<RFC5545>> ACTION property can take the defined values "AUDIO" / "DISPLAY" / "EMAIL"
whereas the JSCalendar "action" property only supports "display" and "email".

An "AUDIO" alarm SHOULD be mapped to a "display" alert. Any attachment MUST be ignored.

The iCalendar DESCRIPTION property is required for both ACTION:EMAIL and ACTION:DISPLAY.
Additionally, the iCalendar SUMMARY property is required for ACTION:EMAIL.

Store the SUMMARY in the optional alert title property and the DESCRIPTION is the alert
description property.

The <<RFC5545>> example VALARMs will be mapped as follows, assuming they are all in the same
event:

[source%unnumbered]
----
BEGIN:VEVENT
DTSTAMP:20200522T142047Z
DTSTART;TZID=America/New_York:20220622T120000
DURATION:PT1H
SUMMARY:event with alarms
UID:6252D6C40A8308BFE25BBEFsimple-alarms-1
BEGIN:VALARM
TRIGGER;VALUE=DATE-TIME:20220508T120000Z
REPEAT:4
DURATION:PT15M
ACTION:AUDIO
ATTACH;FMTTYPE=audio/basic:ftp://example.com/pub/
 sounds/bell-01.aud
END:VALARM
BEGIN:VALARM
TRIGGER:-PT30M
REPEAT:2
DURATION:PT15M
ACTION:DISPLAY
DESCRIPTION:Breakfast meeting with executive\n
 team at 8:30 AM EST.
END:VALARM
BEGIN:VALARM
TRIGGER;RELATED=END:-P2D
ACTION:EMAIL
ATTENDEE:mailto:john_doe@example.com
SUMMARY:*** REMINDER: SEND AGENDA FOR WEEKLY STAFF MEETING ***
DESCRIPTION:A draft agenda needs to be sent out to the attendees
  to the weekly managers meeting (MGR-LIST). Attached is a
  pointer the document template for the agenda file.
ATTACH;FMTTYPE=application/msword:http://example.com/
 templates/agenda.doc
END:VALARM
END:VEVENT

maps to

{
  "@type": "Group",
  "prodId": "//example.org//Example V3.14//EN",
  "entries": [
    {
      "@type": "Event",
      "alerts": {
        "1": {
          "@type": "Alert",
          "action": "display",
          "trigger": {
            "@type": "AbsoluteTrigger",
            "when": "2022-05-08T12:00:00Z"
          }
        },
        "2": {
          "@type": "Alert",
          "action": "display",
          "description": "Breakfast meeting with executive\n
                     team at 8:30 AM EST.",
          "trigger": {
            "@type": "OffsetTrigger",
            "offset": "-PT30M"
          }
        },
        "3": {
          "@type": "Alert",
          "action": "email",
          "title": "*** REMINDER: SEND AGENDA FOR WEEKLY
                    STAFF MEETING ***",
          "description": "A draft agenda needs to be sent out to
                  the attendees to the weekly managers meeting
                  (MGR-LIST). Attached is a pointer the document
                  template for the agenda file.",
          "trigger": {
            "@type": "OffsetTrigger",
            "offset": "-P-2D",
            "relativeTo": "end"
          }
        }
      },
      "created": "2022-05-02T20:04:12Z",
      "start": "2022-06-22T12:00:00",
      "timeZone": "America/New_York",
      "duration": "PT1H",
      "title": "event with alarms",
      "uid": "6252D6C40A8308BFE25BBEFsimple-alarms-1"
    }
  ]
}
----

Note that the ATTENDEE, DURATION and REPEAT properties have been dropped.

=== VCALENDAR

A <<RFC5545>> VCALENDAR component may be mapped to a JSCalendar object with a type of "Group".

[source%unnumbered]
----
BEGIN: VCALENDAR
PRODID:-//ABC Corporation//NONSGML My Product//EN
...
END: VCALENDAR

maps to

{
  "@type": "Group",
  "prodid": "-//ABC Corporation//NONSGML My Product//EN",
  ...
}
----

Note that a single Event or Task MAY be converted without a surrounding Group if the
VCALENDAR component only contains PRODID and CALSCALE properties. In this case the prodid can
go in the Event or Task. The CALSCALE property is dropped - there is no equivalence in
JSCalendar.

=== VEVENT

A <<RFC5545>> VEVENT component is mapped to a JSCalendar object with a type of "Event".

[source%unnumbered]
----
BEGIN: VEVENT
...
END: VEVENT

maps to

{
  "@type": "Event",
  ...
}
----

=== VLOCATION

A <<RFC9073>> VLOCATION component is mapped to a JSCalendar object with a type of "Location".
Any properties within the VLOCATION must be mapped as described below.

[source%unnumbered]
----
BEGIN: VEVENT
...
BEGIN: VLOCATION
...
END: VLOCATION
END: VEVENT

maps to

{
  "@type": "Event",
  ...
   "locations": {
     "1": {
       "@type": "Location",
       ...
     }
   }
}
----

=== VTIMEZONE, STANDARD, DAYLIGHT

A <<RFC5545>> VTIMEZONE component is mapped to a member of a JSCalendar "timezones" object
with a type of "TimeZone" and an id which follows the restrictions specified.

The STANDARD and DAYLIGHT components map to JSCalendar TimeZoneRule objects as members of the

Note that

* There is no current approach for defining standalone sets of timezones.
* Timezones defined in the IANA timezone database SHOULD NOT be redefined in the object. Only
custom timezones will be defined.

[source%unnumbered]
----
BEGIN: VTIMEZONE
TZID: Example/Somewhere
...
END: VTIMEZONE
BEGIN: VTIMEZONE
TZID: Example/Somewhere-else
...
END: VTIMEZONE
BEGIN: VEVENT
...
END: VEVENT

maps to

{
  "@type": "Event",
  ...
  "timezones": {
    "/Example/Somewhere: {
      "@type": "TimeZone",
      "tzId": "Example/Somewhere",
      ...
    },
    "/Example/Somewhere-else": {
      "@type": "TimeZone",
      "tzId": "Example/Somewhere-else",
      ...
    }
  }
}
----

=== VTODO

A <<RFC5545>> VTODO component is mapped to a JSCalendar object with a type of "Task".

[source%unnumbered]
----
BEGIN: VTODO
...
END: VTODO

maps to

{
  "@type": "Task",
  ...
}
----
