[[translate-jscalendar-properties]]
== Translating JSCalendar properties to iCalendar

This section is an alphabetic list of all JSCalendar top-level properties that map to
<<RFC5545>> iCalendar.

=== alerts

Each member of a JSCalendar alerts property maps to a <<RFC5545>> VALARM component. Only
display and email alarms are allowed in JSCalendar.

==== action

The JSCalendar "action" property maps to the <<RFC5545>> ACTION property. The value SHOULD be
the uppercased version of the JSCalendar "alert" property.

For example:

[source%unnumbered]
----
 ...
 "action": "display",
 ...

maps to

 ACTION:DISPLAY

and

 ...
 "action": "email",
 ...

maps to

 ACTION:EMAIL
----

==== title and description

The iCalendar DESCRIPTION property is required for both ACTION:EMAIL and ACTION:DISPLAY.
Additionally, the iCalendar SUMMARY property is required for ACTION:EMAIL.

Both of these are optional in a JSCalendar alert. When converting is there is a title
property in the alert use that for the SUMMARY.

Similarly if a JSCalendar description property is present use that for the description.
Otherwise use the alert title property and if that is absent use the event title.

==== trigger

A JSCalendar trigger with a type of "AbsoluteTrigger" maps on to a <<RFC5545>> TRIGGER
property with a "VALUE" parameter of "DATE-TIME" and a value taken from the JSCalendar "when"
property.

For example:

[source%unnumbered]
----
 "trigger": {
   "@type": "AbsoluteTrigger",
   "when": "20210315T133000Z"
 }

maps to

 TRIGGER;VALUE=DATE-TIME:20210315T133000Z
----

A JSCalendar trigger with a type of "OffsetTrigger" maps on to a <<RFC5545>> TRIGGER property
with a duration value taken from the JSCalendar "offset" property.

If the JSCalendar trigger has a "relativeTo" property with the value "end" then the
<<RFC5545>> TRIGGER property will have a RELATED=END parameter.

For example:

[source%unnumbered]
----
 "trigger": {
   "@type": "OffsetTrigger",
   "offset": "-P2D",
   "relativeTo": "end"
 }

maps to

 TRIGGER;RELATED=END:-P2D

and

   "trigger": {
   "@type": "OffsetTrigger",
   "offset": "-PT30M"
 }

maps to

TRIGGER:-PT30M
----

==== todo

Need to deal with "acknowledged" and "relatedTo". Also in the icalendar to jscalendar.

==== Example event with alerts

[source%unnumbered]
----
{
  "@type": "Group",
  "prodId": "//Example.org//Example V3.14//EN",
  "entries": [
    {
      "@type": "Event",
      "alerts": {
        "1": {
          "@type": "Alert",
          "action": "display",
          "trigger": {
            "@type": "AbsoluteTrigger",
            "when": "2022-05-08T12:00:00Z"
          }
        },
        "2": {
          "@type": "Alert",
          "action": "display",
          "description": "Breakfast meeting with executive\nteam
                          at 8:30 AM EST.",
          "trigger": {
            "@type": "OffsetTrigger",
            "offset": "-PT30M"
          }
        },
        "3": {
          "@type": "Alert",
          "action": "email",
          "title": "*** REMINDER: SEND AGENDA FOR WEEKLY
                    STAFF MEETING ***",
          "description": "A draft agenda needs to be sent out to
                    the attendees to the weekly managers meeting
                    (MGR-LIST). Attached is a pointer the document
                    template for the agenda file.",
          "trigger": {
            "@type": "OffsetTrigger",
            "offset": "-P-2D",
            "relativeTo": "end"
          }
        }
      },
      "created": "2022-05-02T20:04:12Z",
      "start": "2022-06-22T12:00:00",
      "timeZone": "America/New_York",
      "duration": "PT1H",
      "title": "event with alarms",
      "uid": "6252D6C40A8308BFE25BBEFsimple-alarms-1"
    }
  ]
}
maps to

BEGIN:VEVENT
CREATED:20220502T200412Z
DURATION:PT1H
DTSTAMP:20220502T201921Z
DTSTART;TZID=America/New_York:20220622T120000
LAST-MODIFIED:20220502T201921Z
SUMMARY:event with alarms
UID:6252D6C40A8308BFE25BBEFsimple-alarms-1
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;RELATED=START:-PT30M
DESCRIPTION:event with alarms
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DATE-TIME:20220508T120000Z
DESCRIPTION:event with alarms
END:VALARM
BEGIN:VALARM
ACTION:EMAIL
TRIGGER;RELATED=END:-P2D
DESCRIPTION:A draft agenda needs to be sent out to the attendees
  to the weekly managers meeting (MGR-LIST). Attached is a pointe
 r the document template for the agenda file.
SUMMARY:*** REMINDER: SEND AGENDA FOR WEEKLY STAFF MEETING ***
END:VALARM
END:VEVENT
----

=== categories

Each member of the JSCalendar "categories" property maps on to a <<RFC9073>> CONCEPT property
with the value being the key of each member.

For example:

[source%unnumbered]
----
 ...
 "categories": {
   "http://example.com/event-types/arts/music": true,
   "http://example.com/performance-types/arts/live": true
 }
 ...

maps to

 ...
 CONCEPT:http://example.com/event-types/arts/music
 CONCEPT:http://example.com/performance-types/arts/live
 ...
----

=== color

The value is copied verbatim to the <<RFC7986>> "COLOR" property.

=== created

The JSCalendar "created" property maps on to a <<RFC5545>> CREATED property with the value
being the <<RFC5545>> UTC date-time derived from the value of the property.

For example:

[source%unnumbered]
----
 ...
 "created": "2021-03-15T13:30"00Z"
 ...

maps to

 ...
 CREATED:20210315T133000Z
 ...
----

=== duration

The JSCalendar "duration" property is only valid for event objects. Copy the JSCalendar
"duration" property in to the <<RFC5545>> DURATION property.

For example:

[source%unnumbered]
----
 ...
 "duration": "PT1H"
 ...

maps to

 ...
 DURATION:PT1H
 ...
----

=== estimatedDuration

The JSCalendar "estimatedDuration" property is only valid for task objects. Copy the
JSCalendar "estimatedDuration" property in to the <<RFC5545>> ESTIMATED-DURATION property.

For example:

[source%unnumbered]
----
 ...
 "estimatedDuration": "PT18H"
 ...

maps to

 ...
 ESTIMATED-DURATION:PT18H
 ...
----

=== keywords

Each member of the JSCalendar "keywords" property maps on to a <<RFC5545>> CATEGORIES
property with the value being the key of each member.

For example:

[source%unnumbered]
----
 ...
 "keywords": {
      "APPOINTMENT": true,
      "EDUCATION": true,
      "MEETING": true
    },
 ...

maps to

 ...
 CATEGORIES:APPOINTMENT
 CATEGORIES:EDUCATION
 CATEGORIES:MEETING
 ...

 or alternatively

 ...
 CATEGORIES:APPOINTMENT,EDUCATION,MEETING
 ...
----

=== locations

JSCalendar locations map to <<RFC9073>> VLOCATION components.

Additionally, for backwards compatibility, one location should be mapped on to a <<RFC5545>>
LOCATION property.

==== coordinates

TODO. Need to decide if to use GEO or define new GEO-URI.

==== description

The "description" property maps to the DESCRIPTON property value of the VLOCATION.

==== links

TODO. First need to define top-level links property mapping.

==== locationTypes

The keys of the "locationTypes" property map to the LOCATION-TYPE property value of the
VLOCATION. The keys MUST be separated by the COMMA character (U+002c) and SHOULD sort in
ascending alphabetical order.

==== name

The "name" property maps to the NAME property value of the VLOCATION.

==== relativeTo

The "relativeTo" property maps to the RELATED-TO property value of the VLOCATION. TODO need
updated definition of the RELATED-TO draft.

==== timeZone

The "timeZone" property maps to the TZID property value of the VLOCATION.

If the TimeZoneId value matches a name from the IANA Time Zone Database <<TZDB>> then this
value MUST be set in the TZID property.

If the TimeZoneId identifies a custom TimeZone in the JSCalendar object, then the TZID
property value MUST be set to the "tzId" property value of the custom TimeZone object, and
its related VTIMEZONE added to the VCALENDAR component that encloses the VLOCATION.

==== uid

The "uid" property maps to the UID property value of the VLOCATION. The identifier of the
Location object in the enclosing "locations" property maps to the JMAP-ID property parameter.
The parameter MAY be omitted if the identifier of the Location matches the "uid" value.

=== participants

JSCalendar participants will be mapped on to different iCalendar properties and components
depending on their jsCalendar role values.

A participant with a role containing "contact" MUST be mapped on to an iCalendar CONTACT
property and SHOULD also be mapped on to a <<RFC9073>> PARTICIPANT component which provides a
better mapping.

A participant with a role containing "owner" MUST be mapped on to an iCalendar ORGANIZER
property and SHOULD also be mapped on to a <<RFC9073>> PARTICIPANT component which provides a
better mapping.

A participant with a role containing any of "attendee", "optional" or "informational" MUST be
mapped on to an iCalendar ATTENDEE property and SHOULD also be mapped on to a
<<RFC9073>> PARTICIPANT component which provides a better mapping.

A more complete mapping may be achieved by creating a <<RFC9073>> PARTICIPANT component.

For all properties the participants jsCalendar "language" property, if present, is mapped on
to the iCalendar "LANG" property parameter.

For all properties if the participant contains a jsCalendar "link" with a "rel" of
"alternate" then the value of the link is used for the iCalendar "ALTREP" property parameter.

Where do we get the cua?

=== timezones

The JSCalendar TimeZone objects within a "timezones" property are mapped on to <<RFC5545>>
VTIMEZONE components within the surrounding VCALENDAR component. Each mapped TimeZone MUST
only appear once.

[source%unnumbered]
----
{
  "@type": "Event",
  ...
  "timezones": {
    "/Example/Somewhere: {
      "@type": "TimeZone",
      "tzId": "Example/Somewhere",
      ...
    },
    "/Example/Somewhere-else": {
      "@type": "TimeZone",
      "tzId": "Example/Somewhere-else",
      ...
    }
  }
}

maps to

BEGIN: VTIMEZONE
TZID: Example/Somewhere
...
END: VTIMEZONE
BEGIN: VTIMEZONE
TZID: Example/Somewhere-else
...
END: VTIMEZONE
BEGIN: VEVENT
...
END: VEVENT
----

When converting multiple Event or Task objects the surrounding <<RFC5545>> VCALENDAR object
must have a <<RFC5545>> PRODID set from either the Group "prodid" or generated.
