[[jscalendar-props]]
== Common JSCalendar Properties

This section describes the properties that are common to the various JSCalendar object types.
Specific JSCalendar object types may only support a subset of these properties. The object
type definitions in <<jscalendar-object-props>> describe the set of supported properties per
type.

[[metadata-properties]]
=== Metadata Properties

[[prop-type]]
==== @type

Type: `String` (mandatory).

This specifies the type this object represents. The allowed value differs by object type and is
defined in sections <<jsevent>>, <<jstask>>, and <<jsgroup>>

[[prop-uid]]
==== uid

Type: `String` (mandatory).

This is a globally unique identifier used to associate objects representing the same object
across different systems, calendars, and views. For recurring events and tasks, the UID is
associated with the base object and therefore is the same for all occurrences; the
combination of the UID with a `recurrenceId` identifies a particular instance.

The generator of the identifier *MUST* guarantee that the identifier is unique.
<<RFC4122>> describes a range of established algorithms to generate universally
unique identifiers (UUIDs). UUID version 4, described in <<RFC4122,section=4.4>>, is
*RECOMMENDED*.

For compatibility with UIDs <<RFC5545>>, implementations *MUST* be able to receive and persist
values of at least 255 octets for this property, but they *MUST NOT* truncate values in the
middle of a UTF-8 multi-octet sequence.

[[prop-relatedTo]]
==== relatedTo

Type: `String[Relation]` (optional).

This relates the object to other JSCalendar objects. This is represented as a map of the UIDs of
the related objects to information about the relation.

If an object is split to make a "this and future" change to a recurrence, the original object
*MUST* be truncated to end at the previous occurrence before this split, and a new object is
created to represent all the occurrences after the split. A `next` relation MUST be set on
the original object's relatedTo property for the UID of the new object. A `first` relation
for the UID of the first object in the series *MUST* be set on the new object. Clients can then
follow these UIDs to get the complete set of objects if the user wishes to modify them all at
once.

[[prop-prodId]]
==== prodId

Type: `String` (optional).

This is the identifier for the product that last updated the JSCalendar object. This should be set
whenever the data in the object is modified (i.e., whenever the `updated` property is set).

The vendor of the implementation *MUST* ensure that this is a globally unique identifier, using
some technique such as an a Formal Public Identifier (FPI) value, as defined in <<ISO.9070.1991>>.

This property *SHOULD NOT* be used to alter the interpretation of a JSCalendar object beyond
the semantics specified in this document. For example, it is not to be used to further the
understanding of nonstandard properties, a practice that is known to cause long-term
interoperability problems.

[[prop-created]]
==== created

Type: `UTCDateTime` (optional).

This is the date and time this object was initially created.

[[prop-updated]]
==== updated

Type: `UTCDateTime` (mandatory).

This is the date and time the data in this object was last modified (or its creation date/time if not
modified since).

[[prop-sequence]]
==== sequence

Type: `UnsignedInt` (optional, default: 0).

Initially zero, this *MUST* be incremented by one every time a change is made to the object,
except if the change only modifies the `participants` property (see <<prop-participants>>).

This is used as part of iCalendar Transport-independent Interoperability Protocol
(iTIP) <<RFC5546>> to know which version of the object a scheduling
message relates to.

[[prop-method]]
==== method

Type: `String` (optional).

This is the iTIP <<RFC5546>> method, in lowercase. This *MUST* only be present if the JSCalendar object
represents an iTIP scheduling message.

[[whatwhere-properties]]
=== What and Where Properties

[[prop-title]]
==== title

Type: `String` (optional, default: empty String).

This is a short summary of the object.

[[prop-description]]
==== description

Type: `String` (optional, default: empty String).

This is a longer-form text description of the object. The content is formatted according to the
`descriptionContentType` property.

[[prop-descriptionContentType]]
==== descriptionContentType

Type: `String` (optional, default: `text/plain`).

This describes the media type <<RFC6838>> of the contents of the `description` property. Media
types *MUST* be subtypes of type `text`, and *SHOULD* be `text/plain` or `text/html`
<<MEDIATYPES>>.
The media type value *MUST NOT* include parameters. Descriptions of type `text/html`
MAY contain `cid` URLs <<RFC2392>> to
reference links in the calendar object by use of the `cid` property of the Link object.

[[prop-timeZone]]
==== timeZone

Type: `TimeZoneId|null` (optional, default: null).

This identifies the time zone the object is scheduled in or is null for floating
time. This is either a name from the IANA Time Zone Database <<TZDB>> or the
TimeZoneId of a custom time zone defined in the Group `timeZones` property
<<prop-timeZones>>, of which the calendar object is a member of.

If omitted, this *MUST* be presumed to be null (i.e., floating time).

[[prop-showWithoutTime]]
==== showWithoutTime

Type: `Boolean` (optional, default: false).

This indicates that the time is not important to display to the user when rendering this calendar
object. An example of this is an event that conceptually occurs all day or across multiple
days, such as "New Year's Day" or "Italy Vacation". While the time component is important for
free-busy calculations and checking for scheduling clashes, calendars may choose to omit
displaying it and/or display the object separately to other objects to enhance the user's
view of their schedule.

Such events are also commonly known as "all-day" events.

[[prop-locations]]
==== locations

Type: `Id[Location]` (optional).

This is a map of location ids to Location objects, representing locations associated with the object.

A Location object has the following properties. It *MUST* have at least one property other than
the `relativeTo` property.

* @type: `String` (mandatory)
+
This specifies the type of this object. This *MUST* be `Location`.
* uid: `String` (optional)
+
This is the globally unique identifier of the location. See <<prop-uid>> for the definition of this property.
* title: `String` (optional)
+
This is a short human-readable title of the location.
* description: `String` (optional)
+
This is a human-readable, plain-text description of this location, such as
instructions for accessing it. This may be
an address, set of directions, door access code, etc.
* locationTypes: `String[Boolean]` (optional)
+
This is a set of one or more location types that describe this location. All types *MUST* be from the
"Location Types Registry" <<LOCATIONTYPES>>, as defined in <<RFC4589>>. The set is represented
as a map, with the keys being the location types. The value for each key in the map *MUST* be
true.
* relativeTo: `String` (optional)
+
--
This specifies the relation between this location and the time of the JSCalendar object. This is
primarily to allow events representing travel to specify the location of departure (at the
start of the event) and location of arrival (at the end); this is particularly important if
these locations are in different time zones, as a client may wish to highlight this
information for the user.

The `start` and `end` values of the `relativeTo` property each *MUST* be set in at
most one Location (e.g. an event may only start at a single
location and may only end at one other).

This *MUST* be one of the following values, another value registered in the IANA "JSCalendar
Enum Values" registry, or a vendor-specific value (see <<custom-properties>>). Any value the
client or server doesn't understand should be treated the same as if this property is omitted.

** `start`: The event/task described by this JSCalendar object occurs at this location at the
time the event/task starts.
** `end`: The event/task described by this JSCalendar object occurs at this location at the
time the event/task ends.
--
* timeZone: `TimeZoneId` (optional)
+
This is a time zone for this location.
* coordinates: `String` (optional)
+
This is a `geo:` URI <<RFC5870>> for the location.
* links: `Id[Link]` (optional)
+
This is a map of link ids to Link objects, representing external resources associated with this
location, for example a vCard or image.
If there are no links, this *MUST* be omitted (rather than specified as an empty set).

[[prop-conferences]]
=== conferences

Type: `Id[Conference]` (optional).

This is a map of conference ids to Conference objects, representing online meetings,
such as video conferences or chat rooms.

A Conference object has the following properties.

* @type: `String` (mandatory)
+
This specifies the type of this object. This *MUST* be `Conference`.
* name: `String` (optional, default: empty String)
+
This is the human-readable name of the conference.
* description: `String` (optional)
+
These are human-readable plain-text instructions for accessing this virtual
conference. This may be an access code, etc.
* uri: `String` (mandatory)
+
This is a URI <<RFC3986>> that represents how to connect to this conference.
+
This may be a telephone number (represented using the `tel:` scheme, e.g.,
`tel:+1-555-555-5555`) for a teleconference, a web address for online chat, or any custom URI.
* features: `String[Boolean]` (optional)
+
--
A set of features supported by this virtual conference. The set is represented as a map, with
the keys being the feature. The value for each key in the map *MUST* be true.

The feature *MUST* be one of the following values, another value registered in the IANA
"JSCalendar Enum Values" registry, or a vendor-specific value (see <<custom-properties>>). Any
value the client or server doesn't understand should be treated the same as if this feature
is omitted.

** `audio`: Audio conferencing
** `chat`: Chat or instant messaging
** `feed`: Blog or atom feed
** `moderator`: Provides moderator-specific features
** `phone`: Phone conferencing
** `screen`: Screen sharing
** `video`: Video conferencing
--

[[prop-links]]
==== links

Type: `Id[Link]` (optional).

This is a map of link ids to Link objects, representing external resources associated with the object.

Links with a rel of `enclosure` *MUST* be considered by the client to be attachments for
download.

Links with a rel of `describedby` *MUST* be considered by the client to be alternative
representations of the description.

Links with a rel of `icon` MUST be considered by the client to be images that it may use when
presenting the calendar data to a user. The `display` property may be set to indicate the
purpose of this image.

[[prop-locale]]
==== locale

Type: `String` (optional).

This is the language tag, as defined in <<BCP47>> that best describes the locale used for the text
in the calendar object, if known.

[[prop-keywords]]
==== keywords

Type: `String[Boolean]` (optional).

This is a set of keywords or tags that relate to the object. The set is represented as a map, with
the keys being the keywords. The value for each key in the map *MUST* be true.

[[prop-categories]]
==== categories

Type: `String[Boolean]` (optional).

This is a set of categories that relate to the calendar object. The set is represented as a map, with
the keys being the categories specified as URIs. The value for each key in the map *MUST* be
true.

In contrast to keywords, categories are typically structured. For example, a vendor owning
the domain `example.com` might define the categories
`http://example.com/categories/sports/american-football` and
`http://example.com/categories/music/r-b`.

[[prop-color]]
==== color

Type: `String` (optional).

This is a color clients *MAY* use when displaying this calendar object. The value is a color name taken
from the set of names defined in Section 4.3 of <<COLORS>>, or an RGB value in hexadecimal
notation, as defined in Section 4.2.1 of <<COLORS>>.

[[recurrence-props]]
=== Recurrence Properties

Some events and tasks occur at regular or irregular intervals. Rather than having to copy the
data for every occurrence, there can be a base event with rules to generate recurrences,
and/or overrides that add extra dates or exceptions to the rules.

The recurrence set is the complete set of instances for an object. It is generated by
considering the following properties in order, all of which are optional:

. The `recurrenceRules` property (<<prop-recurrenceRules>>) generates a set of extra date-times
on which the object occurs.
. The `excludedRecurrenceRules` property (<<prop-excludedRecurrenceRules>>) generates a set of
date-times that are to be removed from the previously generated set of date-times on which
the object occurs.
. The `recurrenceOverrides` property (<<prop-recurrenceOverrides>>) defines date-times that
are added or excluded to form the final set. (This property may also contain changes to the
object to apply to particular instances.)

[[prop-recurrenceId]]
==== recurrenceId

Type: `LocalDateTime` (optional).

If present, this JSCalendar object represents one occurrence of a recurring JSCalendar
object. If present the `recurrenceRules` and `recurrenceOverrides` properties *MUST NOT* be
present.

The value is a date-time either produced by the `recurrenceRules` of the base event, or
added as a key to the `recurrenceOverrides` property of the base event.

[[prop-recurrenceIdTimeZone]]
==== recurrenceIdTimeZone

Type: `TimeZoneId|null` (optional, default: null).

Identifies the time zone of the main JSCalendar object, of which this JSCalendar
object is a recurrence instance. This property *MUST* be set if the `recurrenceId`
property is set. It *MUST NOT* be set if the `recurrenceId` property is not set.

[[prop-recurrenceRules]]
==== recurrenceRules

Type: `RecurrenceRule[]` (optional).

This defines a set of recurrence rules (repeating patterns) for recurring calendar objects.

An Event recurs by applying the recurrence rules to the `start` date-time.

A Task recurs by applying the recurrence rules to the `start` date-time, if defined,
otherwise, it recurs by the `due` date-time, if defined. If the task defines neither a `start`
nor `due` date-time, it *MUST NOT* define a `recurrenceRules` property.

If multiple recurrence rules are given, each rule is to be applied, and then the union of the
results are used, ignoring any duplicates.

A RecurrenceRule object is a JSON object mapping of a RECUR value type in iCalendar
<<RFC5545>> <<RFC7529>> and has the same semantics. It has the following properties:

* @type: `String` (mandatory)
+
This specifies the type of this object. This *MUST* be `RecurrenceRule`.
* frequency: `String` (mandatory)
+
--
This is the time span covered by each iteration of this recurrence rule (see <<recurrence-semantics>>
for full semantics). This *MUST* be one of the following values:

** `yearly`
** `monthly`
** `weekly`
** `daily`
** `hourly`
** `minutely`
** `secondly`

This is the FREQ part from iCalendar, converted to lowercase.
--
* interval: `UnsignedInt` (optional, default: 1)
+
This is the interval of iteration periods at which the recurrence repeats. If included, it *MUST* be an
integer >= 1.
+
This is the INTERVAL part from iCalendar.

* rscale: `String` (optional, default: "gregorian")
+
This is the calendar system in which this recurrence rule operates, in lowercase. This *MUST* be either
a CLDR-registered calendar system name <<CLDR>>, or a vendor-specific value (see
<<custom-properties>>).
+
This is the RSCALE part from iCalendar RSCALE <<RFC7529>>, converted to lowercase.

* skip: `String` (optional, default: "omit")
+
This is the behavior to use when the expansion of the recurrence produces invalid dates. This
property only has an effect if the frequency is "yearly" or "monthly". It *MUST* be one of the
following values:
+
--
** `omit`
** `backward`
** `forward`

This is the SKIP part from iCalendar RSCALE <<RFC7529>>, converted to lowercase.
--

* firstDayOfWeek: `String` (optional, default: "mo")
+
This is the day on which the week is considered to start, represented as a lowercase, abbreviated, and
two-letter English day of the week. If included, it *MUST* be one of the following values:
+
--
** `mo`
** `tu`
** `we`
** `th`
** `fr`
** `sa`
** `su`

This is the WKST part from iCalendar.
--

* byDay: `NDay[]` (optional)
+
These are days of the week on which to repeat. An `NDay` object has the following properties:
+
--
** @type: `String` (mandatory)
+
This specifies the type of this object. This *MUST* be `NDay`.
** day: `String` (mandatory)
+
This is a day of the week on which to repeat; the allowed values are the same as for the
`firstDayOfWeek` RecurrenceRule property.
+
This is the day of the week of the BYDAY part in iCalendar, converted to lowercase.
** nthOfPeriod: `Int` (optional)
+
If present, rather than representing every occurrence of the weekday defined in the `day`
property, it represents only a specific instance within the recurrence period. The value can
be positive or negative, but *MUST NOT* be zero. A negative integer means the nth-last occurrence
within that period (i.e., -1 is the last occurrence, -2 the one before that, etc.).
+
This is the ordinal part of the BYDAY value in iCalendar (e.g., 1 or -3).
--

* byMonthDay: `Int[]` (optional)
+
These are the days of the month on which to repeat. Valid values are between 1 and the maximum number of
days any month may have in the calendar given by the "`rscale`" property, and the negative
values of these numbers. For example, in the Gregorian calendar, valid values are 1 to 31 and
-31 to -1. Negative values offset from the end of the month. The array *MUST* have at least one
entry if included.
+
This is the BYMONTHDAY part in iCalendar.

* byMonth: `String[]` (optional)
+
These are the months in which to repeat. Each entry is a string representation of a number, starting
from "1" for the first month in the calendar (e.g., "1" means January with the Gregorian
calendar), with an optional "L" suffix (see <<RFC7529>>) for leap months (this *MUST* be
uppercase, e.g., "3L"). The array *MUST* have at least one entry if included.
+
This is the BYMONTH part from iCalendar.

* byYearDay: `Int[]` (optional)
+
These are the days of the year on which to repeat. Valid values are between 1 and the maximum number of
days any year may have in the calendar given by the "`rscale`" property, and the negative
values of these numbers. For example, in the Gregorian calendar, valid values are 1 to 366 and
-366 to -1. Negative values offset from the end of the year. The array *MUST* have at least one
entry if included.
+
This is the BYYEARDAY part from iCalendar.

* byWeekNo: `Int[]` (optional)
+
These are the weeks of the year in which to repeat. Valid values are between 1 and the maximum number of
weeks any year may have in the calendar given by the "`rscale`" property, and the negative
values of these numbers. For example, in the Gregorian calendar, valid values are 1 to 53 and
-53 to -1. The array *MUST* have at least one entry if included.
+
This is the BYWEEKNO part from iCalendar.

* byHour: `UnsignedInt[]` (optional)
+
These are the hours of the day in which to repeat. Valid values are 0 to 23. The array *MUST* have at
least one entry if included. This is the BYHOUR part from iCalendar.

* byMinute: `UnsignedInt[]` (optional)
+
These are the minutes of the hour in which to repeat. Valid values are 0 to 59. The array *MUST* have at
least one entry if included.
+
This is the BYMINUTE part from iCalendar.

* bySecond: `UnsignedInt[]` (optional)
+
These are the seconds of the minute in which to repeat. Valid values are 0 to 60. The array *MUST* have
at least one entry if included.
+
This is the BYSECOND part from iCalendar.

* bySetPosition: `Int[]` (optional)
+
These are the occurrences within the recurrence interval to include in the final results. Negative
values offset from the end of the list of occurrences. The array *MUST* have at least one entry
if included. This is the `BYSETPOS` part from iCalendar.

* count: `UnsignedInt` (optional)
+
These are the number of occurrences at which to range-bound the recurrence. This *MUST NOT* be included
if an `until` property is specified.
+
This is the COUNT part from iCalendar.

* until: `LocalDateTime` (optional)
+
These are the date-time at which to finish recurring. The last occurrence is on or before this
date-time. This *MUST NOT* be included if a `count` property is specified. Note that if not
specified otherwise for a specific JSCalendar object, this date is to be interpreted in the
time zone specified in the JSCalendar object's `timeZone` property.
+
This is the UNTIL part from iCalendar.

[[recurrence-semantics]]
===== Interpreting Recurrence Rules

A recurrence rule specifies a set of date-times for recurring calendar objects. A recurrence
rule has the following semantics. Note that wherever "year", "month" or "day of month" is used,
this is within the calendar system given by the "`rscale`" property, which defaults to
"gregorian" if omitted.

. A set of candidates is generated. This is every second within a period defined by the
frequency property value:
** `yearly`: every second from midnight on the first day of a year (inclusive) to midnight the
first day of the following year (exclusive).
+
If skip is not "omit", the calendar system has leap months and there is a `byMonth` property,
generate candidates for the leap months, even if they don't occur in this year.
+
If skip is not "omit" and there is a `byMonthDay` property, presume each month has the maximum
number of days any month may have in this calendar system when generating candidates, even if
it's more than this month actually has.
** `monthly`: every second from midnight on the first day of a month (inclusive) to midnight on
the first of the following month (exclusive).
+
If skip is not "omit" and there is a `byMonthDay` property, presume the month has the maximum
number of days any month may have in this calendar system when generating candidates, even if
it's more than this month actually has.
** `weekly`: every second from midnight (inclusive) on the first day of the week (as defined
by the `firstDayOfWeek` property, or Monday if omitted), to midnight seven days later (exclusive).
** `daily`: every second from midnight at the start of the day (inclusive) to midnight at the
end of the day (exclusive).
** `hourly`: every second from the beginning of the hour (inclusive) to the beginning of the
next hour (exclusive).
** `minutely`: every second from the beginning of the minute (inclusive) to the beginning of
the next minute (exclusive).
** `secondly`: only the second itself.

. Each date-time candidate is compared against all of the byX properties of the rule except
bySetPosition. If any property in the rule does not match the date-time, the date-time is
eliminated. Each byX property is an array; the date-time matches the property if it matches
any of the values in the array. The properties have the following semantics:

** byMonth: The date-time is in the given month.
** byWeekNo: The date-time is in the nth week of the year. Negative numbers mean the nth last
week of the year. This corresponds to weeks according to week numbering, as defined
in ISO.8601.2004, with a week defined as a seven-day period, starting on `thefirstDayOfWeek`
property value or Monday if omitted. Week number one of the calendar year is the first week
that contains at least four days in that calendar year.
+
If the date-time is not valid (this may happen when generating candidates with a `skip`
property in effect), it is always eliminated by this property.
** byYearDay: The date-time is on the nth day of year. Negative numbers mean the nth last day of
the year.
+
If the date-time is not valid (this may happen when generating candidates with a `skip`
property in effect), it is always eliminated by this property.
** byMonthDay: The date-time is on the given day of the month. Negative numbers mean the nth
last day of the month.
** byDay: The date-time is on the given day of the week. If the day is prefixed by a number,
it is the nth occurrence of that day of the week within the month (if frequency is monthly)
or year (if frequency is yearly). Negative numbers mean nth last occurrence within that
period.
** byHour: The date-time has the given hour value.
** byMinute: The date-time has the given minute value.
** bySecond: The date-time has the given second value.

. If a `skip` property is defined and is not "omit", there may be candidates that do not
correspond to valid dates (e.g., February 31st in the Gregorian calendar). In this case, the
properties *MUST* be considered in the order above and:

.. After applying the byMonth filter, if the candidate's month is invalid for the
given year, increment it (if skip is "forward") or decrement it (if skip is
"backward") until a valid month is found, incrementing/decrementing the year as well
if passing through the beginning/end of the year. This only applies to calendar
systems with leap months.
.. After applying the byMonthDay filter, if the day of the month is invalid for the
given month and year, change the date to the first day of the next month (if skip is
"forward") or the last day of the current month (if skip is "backward").
.. If any valid date produced after applying the skip is already a candidate,
eliminate the duplicate. (For example, after adjusting, February 30th and February
31st would both become the same "real" date, so one is eliminated as a duplicate.)

. If a `bySetPosition` property is included, this is now applied to the ordered list
of remaining dates. This property specifies the indexes of date-times to keep; all
others should be eliminated. Negative numbers are indexed from the end of the list,
with -1 being the last item, -2 the second from last, etc.

. Any date-times before the start date of the event are eliminated (see below for why this
might be needed).

. If a `skip` property is included and is not "omit", eliminate any date-times that have
already been produced by previous iterations of the algorithm. (This is not possible if skip
is "omit".)

. If further dates are required (we have not reached the until date, or count limit) skip the
next (interval - 1) sets of candidates, then continue from step 1.

When determining the set of occurrence dates for an event or task, the following extra rules
must be applied:

. The initial date-time to which the rule is applied (the `start` date-time for events or the
`start` or `due` date-time for tasks) is always the first occurrence in the expansion (and is
counted if the recurrence is limited by a "`count`" property), even if it would normally not
match the rule.
. The first set of candidates to consider is that which would contain the initial date-time.
This means the first set may include candidates before the initial date-time; such candidates are
are eliminated from the results in step 4 as outlined above.
. The following properties *MUST* be implicitly added to the rule under the given conditions:

** If frequency is not `secondly` and there is no `bySecond` property, add a `bySecond` property with the
sole value being the seconds value of the initial date-time.
** If frequency is not `secondly` or `minutely`, and there is no `byMinute`
property, add a `byMinute`
property with the sole value being the minutes value of the initial date-time.
** If frequency is not `secondly`, `minutely` or `hourly` and there is no `byHour` property, add a
`byHour` property with the sole value being the hours value of the initial date-time.
** If frequency is `weekly` and there is no `byDay` property, add a `byDay` property with the sole value
being the day of the week of the initial date-time.
** If frequency is `monthly` and there is no `byDay` property and no `byMonthDay` property, add a
`byMonthDay` property with the sole value being the day of the month of the initial date-time.
** If frequency is `yearly` and there is no `byYearDay` property:

*** If there are no `byMonth` or `byWeekNo` properties, and either there is a `byMonthDay` property
or there is no `byDay` property, add a byMonth property with the sole value being the month of
the initial date-time.
*** If there is no `byMonthDay`, `byWeekNo`, or `byDay` properties, add a `byMonthDay` property with
the sole value being the day of the month of the initial date-time.
*** If there is a `byWeekNo` property and no `byMonthDay` or `byDay` properties, add a `byDay`
property with the sole value being the day of the week of the initial date-time.

[[prop-excludedRecurrenceRules]]
==== excludedRecurrenceRules

Type: `RecurrenceRule[]` (optional).

This defines a set of recurrence rules (repeating patterns) for date-times on which the object
will not occur. The rules are interpreted the same as for the "`recurrenceRules`" property (see
<<prop-recurrenceRules>>), with the exception that the initial date-time to which the rule is
applied (the "start" date-time for events or the "start" or "due" date-time for tasks) is only
considered part of the expansion if it matches the rule. The resulting set of date-times is
then removed from those generated by the `recurrenceRules` property, as described in
<<recurrence-props>>.

[[prop-recurrenceOverrides]]
==== recurrenceOverrides

Type: `LocalDateTime[PatchObject]` (optional).

Maps recurrence ids (the date-time produced by the recurrence rule) to the overridden
properties of the recurrence instance.

If the recurrence id does not match a date-time from the recurrence rule (or no rule is
specified), it is to be treated as an additional occurrence (like an RDATE from iCalendar).
The patch object may often be empty in this case.

If the patch object defines the `excluded` property of an occurrence to be true, this
occurrence is omitted from the final set of recurrences for the calendar object (like an
EXDATE from iCalendar). Such a patch object *MUST NOT* patch any other property.

By default, an occurrence inherits all properties from the main object except the start (or
due) date-time, which is shifted to match the recurrence id LocalDateTime. However,
individual properties of the occurrence can be modified by a patch, or multiple patches. It
is valid to patch the `start` property value, and this patch takes precedence over the value
generated from the recurrence id. Both the recurrence id as well as the patched `start`
date-time may occur before the original JSCalendar object's `start` or `due` date.

A pointer in the PatchObject *MUST* be ignored if it starts with one of the following prefixes:

* @type
* excludedRecurrenceRules
* method
* privacy
* prodId
* recurrenceId
* recurrenceIdTimeZone
* recurrenceOverrides
* recurrenceRules
* relatedTo
* replyTo
* sentFrom
* timeZones
* uid

[[prop-excluded]]
==== excluded

Type: `Boolean` (optional, default: false).

This defines if this object is an overridden, excluded instance of a recurring JSCalendar object
(see <<prop-recurrenceOverrides>>). If this property value is true, this calendar object
instance *MUST* be removed from the occurrence expansion. The absence of this property, or the
presence of its default value false, indicates that this instance *MUST* be included in the
occurrence expansion.
If this property is set, then the `recurrenceId` property *MUST* be set.

[[sharing-scheduling-properties]]
=== Sharing and Scheduling Properties

[[prop-priority]]
==== priority

Type: `Int` (optional, default: 0).

This specifies a priority for the calendar object. This may be used as part of scheduling systems
to help resolve conflicts for a time period.

The priority is specified as an integer in the range 0 to 9. A value of 0 specifies an
undefined priority, for which the treatment will vary by situation. A value of 1 is the
highest priority. A value of 2 is the second highest priority. Subsequent numbers specify a
decreasing ordinal priority. A value of 9 is the lowest priority. Other integer values are
reserved for future use.

[[prop-freeBusyStatus]]
==== freeBusyStatus

Type: `String` (optional, default: `busy`).

This specifies how this calendar object should be treated when calculating free-busy state. This
*MUST* be one of the following values, another value registered in the IANA "JSCalendar Enum
Values" registry, or a vendor-specific value (see <<custom-properties>>):

* `free`: The object should be ignored when calculating whether the user is busy.
* `busy`: The object should be included when calculating whether the user is busy.

[[prop-privacy]]
==== privacy

Type: `String` (optional, default: `public`).

Calendar objects are normally collected together and may be shared with other others. The
privacy property allows the object owners to indicate that it should not be shared, or should
only have the time information shared but the details withheld. Enforcement of the
restrictions indicated by this property is up to the API via which this object is accessed.

This property *MUST NOT* affect the information sent to scheduled participants; it is only
interpreted by protocols that share the calendar objects belonging to one user with other
users.

The value *MUST* be one of the following values, another value registered in the IANA
"JSCalendar Enum Values" registry, or a vendor-specific value (see <<custom-properties>>). Any
value the client or server doesn't understand should be preserved but treated as equivalent
to `private`.

* `public`: The full details of the object are visible to anyone it is
shared with.
* `private`: The details of the object are hidden to anyone but the object
owners; only the basic time and metadata are
shared. The following properties *MAY* be shared, any other properties *MUST NOT* be shared:
** @type
** created
** due
** duration
** estimatedDuration
** freeBusyStatus
** privacy
** recurrenceOverrides. Only patches which apply to another permissible property are allowed
to be shared.
** sequence
** showWithoutTime
** start
** timeZone
** timeZones
** uid
** updated
* `secret`: The object is hidden completely (as though it did not exist)
to anyone but the object owners.

[[prop-replyTo]]
==== replyTo

Type: `String[String]` (optional).

This represents methods by which participants may submit their response to the organizer of the
calendar object. The keys in the property value are the available methods and *MUST* only
contain ASCII alphanumeric characters (A-Za-z0-9). The value is a URI for the method
specified in the key. Future methods may be defined in future specifications and registered
with IANA; a calendar client *MUST* ignore any method it does not understand, but *MUST* preserve
the method key and URI. This property *MUST* be omitted if no method is defined (rather than
being specified as an empty object).

The following methods are defined:

* `imip`: The organizer accepts an iCalendar Message-Based Interoperability Protocol
(iMIP) <<RFC6047>> response at this email address. The value
*MUST* be a `mailto:` URI.
* `web`: Opening this URI in a web browser will provide the user with a page where they can
submit a reply to the organizer. The value *MUST* be a URL using the `https:` scheme.
* `other`: The organizer is identified by this URI, but the method for submitting the response
is undefined.

[[prop-replytoscheduleagent]]
==== replyToScheduleAgent

Type: `String` (optional, default: `server`)

This is who is responsible for sending scheduling reply messages for this calendar object.

The value *MUST* be one of the following values, another value registered in the
IANA "JSCalendar Enum Values" registry, or a vendor-specific value
(see <<custom-properties>>):

* `server`:
+
The calendar server will send the scheduling reply messages.
* `client`:
+
The calendar client will send the scheduling reply messages.
* `none`:
+
No scheduling reply messages are to be sent.

[[prop-replytoscheduleforcesend]]
==== replyToScheduleForceSend

Type: `Boolean` (optional, default: false)

A client may set this property to `true` to request that the server send a
scheduling reply when it would not normally do so (e.g., if no significant
change is made the object or the scheduleAgent is set to client). The property
*MUST NOT* be stored in the JSCalendar object on the server or appear in a scheduling
message.

[[prop-replytoschedulestatus]]
==== replyToScheduleStatus

Type: `String` (optional)

This is a list of status codes, returned from the sending of the most recent scheduling reply message.
The status codes MUST be valid `statcode` values as defined in the ABNF
in <<RFC5545,section=3.8.8.3>>.

Servers *MUST* only add or change this property when they send a scheduling
reply. Clients *SHOULD NOT* change or remove this property if
it was provided by the server. Clients *MAY* add, change, or remove the property where
the client is sending the scheduling replies.

This property *MUST NOT* be included in scheduling messages.

[[prop-sentFrom]]
==== sentFrom

Type: `String` (optional)

This is the email address in the "From" header of the email in which this calendar
object was received. This is only relevant if the calendar object is received via
iMIP or as an attachment to a message.  If set, the value *MUST* be a valid
`addr-spec` value as defined in <<RFC5322,section=3.4.1>>.

[[prop-participants]]
==== participants

Type: `Id[Participant]` (optional).

This is a map of participant ids to participants, describing their participation in the calendar
object.

If this property is set and any participant has a `sendTo` property, then the `replyTo`
property of this calendar object *MUST* define at least one reply method.

A Participant object has the following properties:

* @type: `String` (mandatory)
+
This specifies the type of this object. This *MUST* be `Participant`.
* name: `String` (optional)
+
This is the display name of the participant (e.g., "Joe Bloggs").
* email: `String` (optional)
+
This is the email address to use to contact the participant or, for example, match
with an address book entry. If set, the value *MUST* be valid `addr-spec` value as
defined in <<RFC5322,section=3.4.1>>.
* description: `String` (optional).
+
This is a plain-text description of this participant. For example, this may include more information
about their role in the event or how best to contact them.
* scheduleId: `String` (optional)
+
A persistent, global id that represents this participant for scheduling purposes.
The value *MUST* be a URI. This *MAY* be the same as a URI in the `sendTo` property.
* sendTo: `String[String]` (optional)
+
This represents methods by which the participant may receive the invitation and updates to the
calendar object.
+
The keys in the property value are the available methods and *MUST* only contain ASCII
alphanumeric characters (A-Za-z0-9). The value is a URI for the method specified in the key.
Future methods may be defined in future specifications and registered with IANA; a calendar
client *MUST* ignore any method it does not understand, but *MUST* preserve the method key and
URI. This property *MUST* be omitted if no method is defined (rather than being specified as an
empty object).
+
--
The following methods are defined:

** `imip`: The participant accepts an iMIP <<RFC6047>> request at this email address. The
value *MUST* be a `mailto:` URI. It *MAY* be different from the value of the participant's
`email` property.
** `other`: The participant is identified by this URI but the method for submitting the
invitation is undefined.
--
* kind: `String` (optional)
+
--
This is what kind of entity this participant is, if known.

This *MUST* be one of the following values, another value registered in the IANA "JSCalendar
Enum Values" registry, or a vendor-specific value (see <<custom-properties>>). Any value the
client or server doesn't understand should be treated the same as if this property is omitted.

** `individual`: a single person
** `group`: a collection of people invited as a whole
** `location`: a physical location that needs to be scheduled, e.g., a conference room
** `resource`: a non-human resource other than a location, such as a projector
--
* roles: `String[Boolean]` (mandatory)
+
--
This is a set of roles that this participant fulfills.

At least one role *MUST* be specified for the participant. The keys in the set *MUST* be one of
the following values, another value registered in the IANA "JSCalendar Enum Values" registry,
or a vendor-specific value (see <<custom-properties>>):

** `owner`: The participant is an owner of the object. This signifies they have permission to
make changes to it that affect the other participants. Nonowner participants may only change
properties that just affect only themselves (for example, setting their own alerts or changing
their RSVP status).
** `attendee`: The participant is expected to be present at the event.
** `optional`: The participant's involvement with the event is optional. This is expected to
be primarily combined with the "attendee" role.
** `informational`: The participant is copied for informational reasons and is not expected
to attend.
** `chair`: The participant is in charge of the event/task when it occurs.
** `contact`: The participant is someone that may be contacted for information about the
event.

The value for each key in the map *MUST* be true. It is expected that no more than one of the
roles "attendee" and "informational" be present; if more than one are given, "attendee" takes
precedence over "informational". Roles that are unknown to the implementation *MUST* be
preserved.
--

* locations: `Id[Location]` (optional)
+
These are the locations at which this participant is expected to be attending.
See <<prop-locations>> for the definition of this property.

* conferences: `Id[Conference]` (optional)
+
This is online conferencing information that is specific for the participant
See <<prop-conferences>> for the definition of this property.

* language: `String` (optional)
+
This is the language tag, as defined in <<BCP47>>, that best describes
the participant's preferred language, if known.

* participationStatus: `String` (optional, default: `needs-action`)
+
--
This is the participation status, if any, of this participant.

The value *MUST* be one of the following values, another value registered in the
IANA "JSCalendar Enum Values" registry, or a vendor-specific value (see <<custom-properties>>):

** `needs-action`: No status has yet been set by the participant.
** `accepted`: The invited participant will participate.
** `declined`: The invited participant will not participate.
** `tentative`: The invited participant may participate.
** `delegated`: The invited participant has delegated their attendance to another participant, as
specified in the `delegatedTo` property.
** `in-process`: The participant is in process of completing their participation in this task. This value only is allowed for participants of a Task object.
** `completed`: The participant has completed their participation in this task. This value only is allowed for participants of a Task object.
--

* participationComment: `String` (optional)
+
This is a note from the participant to explain their participation status.

* expectReply: `Boolean` (optional, default: false)
+
If true, the organizer is expecting the participant to notify them of their participation
status.

* scheduleAgent: `String` (optional, default: `server`)
+
--
This is who is responsible for sending scheduling messages with this calendar object to the
participant.

The value *MUST* be one of the following values, another value registered in the IANA
"JSCalendar Enum Values" registry, or a vendor-specific value (see <<custom-properties>>):

** `server`: The calendar server will send the scheduling messages.
** `client`: The calendar client will send the scheduling messages.
** `none`: No scheduling messages are to be sent to this participant.
--

* scheduleForceSend: `Boolean` (optional, default: false)
+
A client may set the property on a participant to true to request that the server send a
scheduling message to the participant when it would not normally do so (e.g., if no
significant change is made the object or the scheduleAgent is set to client). The property
*MUST NOT* be stored in the JSCalendar object on the server or appear in a scheduling message.

* scheduleSequence: `UnsignedInt` (optional, default: 0)
+
This is the sequence number of the last response from the participant. If defined, this *MUST* be a
nonnegative integer.
+
This can be used to determine whether the participant has sent a new response following
significant changes to the calendar object and to determine if future responses are
responding to a current or older view of the data.

* scheduleStatus: `String[]` (optional)
+
This is a list of status codes, returned from the processing of the most recent scheduling message
sent to this participant. The status codes *MUST* be valid `statcode` values as defined in the
ABNF in <<RFC5545,section=3.8.8.3>>.
+
Servers *MUST* only add or change this property when they send a scheduling message to the
participant. Clients *SHOULD NOT* change or remove this property if it was provided by the
server. Clients *MAY* add, change, or remove the property for participants where the client is
handling the scheduling.
+
This property *MUST NOT* be included in scheduling messages.

* scheduleUpdated: `UTCDateTime` (optional)
+
This is the timestamp for the most recent response from this participant.
+
This is the `updated` property of the last response when using iTIP. It can be compared to
the `updated` property in future responses to detect and discard older responses delivered
out of order.

* sentFrom: `String` (optional)
+
This is the email address in the "From" header of the email that last updated this
participant via iMIP. This SHOULD only be set if the email address is different to
that in the mailto URI of this participant's `imip` method in the `sendTo` property
(i.e., the response was received from a different address to that which the
invitation was sent to). If set, the value *MUST* be a valid `addr-spec` value as
defined in <<RFC5322,section=3.4.1>>.

* invitedBy: `String` (optional)
+
This is the scheduleId of the participant who added this participant to the event/task, if known.

* delegatedTo: `String[Boolean]` (optional)
+
This is a set of scheduleIds of other participants that this participant has
delegated their participation to.
Each key in the set *MUST* be a URI. The value for each key in the map
*MUST* be true. If there are no delegates, this *MUST* be omitted
(rather than specified as an empty set).

* delegatedFrom: `String[Boolean]` (optional)
+
his is a set of scheduleIds of other participants that this participant is acting
as a delegate for. Each key
in the set *MUST* be a URI. The value for each key in the map
*MUST* be true. If there are no delegators, this *MUST* be omitted
(rather than specified as an empty set).

* memberOf: `String[Boolean]` (optional)
+
This is a set of scheduleIds of group participants that were invited to this
calendar object, which caused this
participant to be invited due to their membership in the group(s). Each key in the set
*MUST* be a URI. The value for each key in the map
*MUST* be true. If there are no groups, this
*MUST* be omitted (rather than specified as an empty set).

* links: `Id[Link]` (optional)
+
This is a map of link ids to Link objects, representing external resources associated with this
participant, for example a vCard or image.
If there are no links, this *MUST* be omitted (rather than specified as an empty set).

* progress: `String` (optional; only allowed for participants of a Task).
+
This represents the progress of the participant for this task. It *MUST NOT* be set if the
`participationStatus` of this participant is any value other than `accepted`. See
<<prop-progress>> for allowed values and semantics.

* progressUpdated: `UTCDateTime` (optional; only allowed for participants of a Task).
+
This specifies the date-time the `progress` property was last set on this participant. See
<<prop-progressUpdated>> for allowed values and semantics.

* percentComplete: `UnsignedInt` (optional; only allowed for participants of a Task).
+
This represents the percent completion of the participant for this task. The property value *MUST*
be a positive integer between 0 and 100.

[[prop-requestStatus]]
==== requestStatus

Type: `String` (optional).

A request status as returned from processing the most recent scheduling request for this
JSCalendar object. The allowed values are defined by the ABNF definitions of `statcode`,
`statdesc` and `extdata` in <<RFC5545,section=3.8.8.3>> and the following ABNF <<RFC5234>>:

[source%unnumbered]
----
reqstatus = statcode ";" statdesc [";" extdata]
----

Servers *MUST* only add or change this property when they performed a scheduling action.
Clients *SHOULD NOT* change or remove this property if it was provided by the server. Clients
*MAY* add, change, or remove the property when the client is handling the scheduling.

This property *MUST* only be included in scheduling messages according to the rules defined
for the REQUEST-STATUS iCalendar property in <<RFC5546>>.

[[alerts-properties]]
=== Alerts Properties

[[useDefaultAlerts]]
==== useDefaultAlerts

Type: `Boolean` (optional, default: false).

If true, use the user's default alerts and ignore the value of the `alerts` property.
Fetching user defaults is dependent on the API from which this JSCalendar object is being
fetched and is not defined in this specification. If an implementation cannot determine the
user's default alerts, or none are set, it *MUST* process the `alerts` property as if
`useDefaultAlerts` is set to false.

[[prop-alerts]]
==== alerts

Type: `Id[Alert]` (optional).

This is a map of alert ids to Alert objects, representing alerts/reminders to display or send to the
user for this calendar object.

An Alert object has the following properties:

* @type: `String` (mandatory)
+
This specifies the type of this object. This *MUST* be `Alert`.
* uid: `String` (optional)
+
This is the globally unique identifier of the alert. See <<prop-uid>> for the
definition of this property.
* trigger: `OffsetTrigger|AbsoluteTrigger|UnknownTrigger` (mandatory)
+
--
This defines when to trigger the alert. New types may be defined in future documents.

An `OffsetTrigger` object has the following properties:

** @type: `String` (mandatory)
+
This specifies the type of this object. This *MUST* be `OffsetTrigger`.
** offset: `SignedDuration` (mandatory).
+
This defines the offset at which to trigger the alert relative to the time property defined in
the `relativeTo` property of the alert. Negative durations signify alerts before the time
property; positive durations signify alerts after the time property.
** relativeTo: `String` (optional, default: `start`)
+
This specifies the time property that the alert offset is relative to. The value *MUST* be one of:

*** `start`: triggers the alert relative to the start of the calendar object
*** `end`: triggers the alert relative to the end/due time of the calendar object

An `AbsoluteTrigger` object has the following properties:

* @type: `String` (mandatory)
+
This specifies the type of this object. This *MUST* be `AbsoluteTrigger`.
* when: `UTCDateTime` (mandatory).
+
This defines a specific UTC date-time when the alert is triggered.

An `UnknownTrigger` object is an object that contains a `@type` property whose value is not
recognized (i.e., not `OffsetTrigger` or `AbsoluteTrigger`) plus zero or more other
properties. This is for compatibility with client extensions and future specifications.
Implementations *SHOULD NOT* trigger for trigger types they do not understand, but *MUST*
preserve them.
--

* acknowledged: `UTCDateTime` (optional)
+
This records when an alert was last acknowledged. This is set when the user has dismissed
the alert; other clients that sync this property *SHOULD* automatically dismiss or suppress
duplicate alerts (alerts with the same alert id that triggered on or before this date-time).
+
For a recurring calendar object, setting the `acknowledged` property *MUST NOT* add a new
override to the `recurrenceOverrides` property. If the alert is not already overridden, the
acknowledged property *MUST* be set on the alert in the base event/task.
+
Certain kinds of alert action may not provide feedback as to when the user sees them, for
example, email-based alerts. For those kinds of alerts, this property *MUST* be set immediately
when the alert is triggered and the action successfully carried out.

* relatedTo: `String[Relation]` (optional)
+
This relates this alert to other alerts in the same JSCalendar object. If the user wishes to
snooze an alert, the application *MUST* create an alert to trigger after snoozing. This new
snooze alert *MUST* set a parent relation to the identifier of the original alert.

* action: `String` (optional, default: `display`)
+
--
This describes how to alert the user.

The value *MUST* be at most one of the following values, a value registered in the IANA
"JSCalendar Enum Values" registry, or a vendor-specific value (see <<custom-properties>>):

** `display`: The alert should be displayed as appropriate for the current device and user
context.
** `email`: The alert should trigger an email sent out to the user, notifying them of the
alert. This action is typically only appropriate for server implementations.
--

[[localized-props]]
=== Multilingual Properties

[[prop-localizations]]
==== localizations

Type: `String[PatchObject]` (optional).

A map where each key is a language tag <<BCP47>>, and the value is a PatchObject
<<type-PatchObject>>, that localizes the patch target properties in that language.
The value type of the patched property *MUST* be `String` and the property *SHOULD*
contain human-readable text. A patch pointer *MUST NOT* have the prefix `recurrenceOverrides`;
instead, the override should define its own `localizations` property.

This specification does not define how to maintain validity of localized content.
For example, a client application changing a JSCalendar object's `title` property
might also need to update any localizations of this property. Client
implementations *SHOULD* provide the means to manage localizations, but how to
achieve this is specific to the application workflow and requirements.
