== IANA Considerations

=== Media Type Registration

This document defines a media type for use with JSCalendar data formatted in JSON.

Type name:: application

Subtype name:: jscalendar+json

Required parameters:: type
+
The `type` parameter conveys the type of the JSCalendar data in the body part.
The allowed parameter values correspond to the `@type` property of the
JSON-formatted JSCalendar object in the body:
+
--
`event`:::
The `@type` property value *MUST* be `Event`.

`task`:::
The `@type` property value *MUST* be `Task`.

`group`:::
The `@type` property value *MUST* be `Group`.
--
+
No other parameter values are allowed. The parameter *MUST NOT* occur more than once.

Optional parameters:: none

Encoding considerations:: This is the same as the encoding considerations of
application/json, as specified in <<RFC8259,section=11>>.

Security considerations:: See <<security-considerations>> of this document.

Interoperability considerations:: While JSCalendar is designed to avoid
ambiguities as much as possible, when converting objects from other calendar
formats to/from JSCalendar, it is possible that differing representations for
the same logical data or ambiguities in interpretation might arise. The semantic
equivalence of two JSCalendar objects may be determined differently by different
applications, for example, where URL values differ in case between the two
objects.

Published specification:: RFC 8984

Applications that use this media type:: Applications that currently make use of
the text/calendar and application/calendar+json media types can use this as an
alternative. Similarly, applications that use the application/json media type to
transfer calendaring data can use this to further specify the content.

Fragment identifier considerations:: A JSON Pointer fragment identifier may be
used, as defined in <<RFC6901,section=6>>.

Additional information::
Magic number(s)::: N/A
File extensions(s)::: N/A
Macintosh file type code(s)::: N/A

Person & email address to contact for further information:: calsify@ietf.org

Intended usage:: COMMON

Restrictions on usage:: N/A

Author:: See the "Author's Address" section of this document.

Change controller:: IETF

[[iana-property-registry]]
=== Changes to the "JSCalendar Properties" Registry

When <<RFC8984>> was published, IANA has created the "JSCalendar Properties"
registry to allow interoperability of extensions to JSCalendar objects. As this
RFC document obsoletes <<RFC8984>> the IANA registry contents and update rules
shall be completely replaced with the following definitions.

This registry follows the Expert Review process (<<RFC8126,section=4.5>>). If
the "Intended Usage" field is `common`, sufficient documentation is required to
enable interoperability. Preliminary community review for this registry is
optional but strongly encouraged.

A registration can have an intended usage of `common`, `reserved`, or
`obsolete`. IANA will list registrations with a common usage designation
prominently and separately from those with other intended usage values.

A `reserved` registration reserves a property name without assigning semantics
to avoid name collisions with future extensions or protocol use.

An `obsolete` registration denotes a property that is no longer expected to be
added by up-to-date systems. A new property has probably been defined covering
the obsolete property's semantics.

The JSCalendar property registration procedure is not a formal standards process
but rather an administrative procedure intended to allow community comment and
check it is coherent without excessive time delay. It is designed to encourage
vendors to document and register new properties they add for use cases not
covered by the original specification, leading to increased interoperability.

==== Preliminary Community Review

Notice of a potential new registration *SHOULD* be sent to the Calext mailing
list <calsify@ietf.org> for review. This mailing list is appropriate to solicit
community feedback on a proposed new property.

Property registrations must be marked with their intended use: "common",
"reserved", or "obsolete".

The intent of the public posting to this list is to solicit comments and
feedback on the choice of the property name, the unambiguity of the
specification document, and a review of any interoperability or security
considerations. The submitter may submit a revised registration proposal or
abandon the registration completely at any time.

==== Submit Request to IANA

Registration requests can be sent to <iana@iana.org>.

==== Designated Expert Review

The primary concern of the designated expert (DE) is preventing name collisions
and encouraging the submitter to document security and privacy considerations.
For a common-use registration, the DE is expected to confirm that suitable
documentation, as described in <<RFC8126,section=4.6>>, is available to ensure
interoperability. That documentation will usually be in an RFC, but simple
definitions are likely to use a web/wiki page, and if a sentence or two is
deemed sufficient, it could be described in the registry itself. The DE should
also verify that the property name does not conflict with work that is active or
already published within the IETF. A published specification is not required for
reserved or obsolete registrations.

The DE will either approve or deny the registration request and publish a notice
of the decision to the Calext WG mailing list or its successor, as well as
inform IANA. A denial notice must be justified by an explanation, and, in the
cases where it is possible, concrete suggestions on how the request can be
modified so as to become acceptable should be provided.

==== Change Procedures

Once a JSCalendar property has been published by IANA, the change controller may
request a change to its definition. The same procedure that would be appropriate
for the original registration request is used to process a change request.

JSCalendar property registrations may not be deleted; properties that are no
longer believed appropriate for use can be declared obsolete by a change to
their "intended usage" field; such properties will be clearly marked in the IANA
registry.

Significant changes to a JSCalendar property's definition should be requested
only when there are serious omissions or errors in the published specification,
as such changes may cause interoperability issues. When review is required, a
change request may be denied if it renders entities that were valid under the
previous definition invalid under the new definition.

The owner of a JSCalendar property may pass responsibility to another person or
agency by informing IANA; this can be done without discussion or review.

==== "JSCalendar Properties" Registry Template

Property Name:: This is the name of the property. The property name *MUST NOT*
already be registered for any of the object types listed in the "Property
Context" field of this registration. Other object types *MAY* already have
registered a different property with the same name; however, the same name
*SHOULD* only be used when the semantics are analogous.

Property Type:: This is the type of this property, using type signatures, as
specified in <<type-signatures>>. The property type *MUST* be registered in the
"JSCalendar Types" registry.

Property Context:: This is a comma-separated list of JSCalendar object types
this property is allowed on.

Reference or Description:: This is a brief description or RFC number and section
reference where the property is specified (omitted for "reserved" property
names).

Intended Usage:: This may be "common", "reserved", or "obsolete".

Change Controller:: This is who may request a change to this entry's definition
(`IETF` for RFCs from the IETF stream).

=== Initial Contents for the "JSCalendar Properties" Registry

The following table lists the initial entries of the "JSCalendar Properties"
registry. All properties are for common use. All RFC section references are for
this document. The change controller for all these properties is "IETF".

[options=header,cols=4]
.Initial Contents of the "JSCalendar Properties" Registry
|===
| Property Name | Property Type | Property Context | Reference or Description

|@type |String |Event, Task, Group, AbsoluteTrigger, Alert, Link, Location, NDay, OffsetTrigger, Participant, RecurrenceRule, Relation, TimeZone, TimeZoneRule, Conference | <<prop-type>>, <<prop-alerts>>, <<type-Link>>, <<prop-locations>>, <<prop-participants>>, <<prop-recurrenceRules>>, <<type-Relation>>, <<prop-timeZones>>, <<prop-conferences>>

|acknowledged |UTCDateTime |Alert |<<prop-alerts>>

|action |String |Alert |<<prop-alerts>>

|alerts |Id[Alert] |Event, Task |<<prop-alerts>>

|aliases |String[Boolean] |TimeZone |<<prop-timeZones>>

|byDay |NDay[] |RecurrenceRule |<<prop-recurrenceRules>>

|byHour |UnsignedInt[] |RecurrenceRule |<<prop-recurrenceRules>>

|byMinute |UnsignedInt[] |RecurrenceRule |<<prop-recurrenceRules>>

|byMonth |String[] |RecurrenceRule |<<prop-recurrenceRules>>

|byMonthDay |Int[] |RecurrenceRule |<<prop-recurrenceRules>>

|bySecond |UnsignedInt[] |RecurrenceRule |<<prop-recurrenceRules>>

|bySetPosition |Int[] |RecurrenceRule |<<prop-recurrenceRules>>

|byWeekNo |Int[] |RecurrenceRule |<<prop-recurrenceRules>>

|byYearDay |Int[] |RecurrenceRule |<<prop-recurrenceRules>>

|categories |String[Boolean] |Event, Task, Group |<<prop-categories>>

|cid |String |Link |<<type-Link>>

|color |String |Event, Task, Group |<<prop-color>>

|comments |String[] |TimeZoneRule |<<prop-timeZones>>

|conferences |Id [Conference] |Event, Task, Participant |<<prop-conferences>>

|contentType |String |Link |<<type-Link>>

|coordinates |String |Location |<<prop-locations>>

|count |UnsignedInt |RecurrenceRule |<<prop-recurrenceRules>>

|created |UTCDateTime |Event, Task, Group |<<prop-created>>

|day |String |NDay |<<prop-recurrenceRules>>

|daylight |TimeZoneRule[] |TimeZone |<<prop-timeZones>>

|delegatedFrom |Id[Boolean] |Participant |<<prop-participants>>

|delegatedTo |Id[Boolean] |Participant |<<prop-participants>>

|description |String |Event, Task, Location, Participant, Conference |<<prop-description>>, <<prop-locations>>, <<prop-participants>>, <<prop-conferences>>

|description ContentType |String |Event, Task |<<prop-descriptionContentType>>

|display |String |Link |<<type-Link>>

|due |LocalDateTime |Task |<<prop-due>>

|duration |Duration |Event |<<prop-duration>>

|email |String |Participant |<<prop-participants>>

|entries |(Task\|Event)[] |Group |<<prop-entries>>

|estimatedDuration |Duration |Task |<<prop-estimatedDuration>>

|excluded |Boolean |Event, Task |<<prop-excluded>>

|excluded RecurrenceRules |RecurrenceRule[] |Event, Task |<<prop-excludedRecurrenceRules>>

|expectReply |Boolean |Participant |<<prop-participants>>

|features |String[Boolean] |Conference |<<prop-conferences>>

|firstDayOfWeek |String |RecurrenceRule |<<prop-recurrenceRules>>

|freeBusyStatus |String |Event, Task |<<prop-freeBusyStatus>>

|frequency |String |RecurrenceRule |<<prop-recurrenceRules>>

|href |String |Link |<<type-Link>>

|interval |UnsignedInt |RecurrenceRule |<<prop-recurrenceRules>>

|invitedBy |Id |Participant |<<prop-participants>>

|keywords |String[Boolean] |Event, Task, Group |<<prop-keywords>>

|kind |String |Participant |<<prop-participants>>

|language |String |Participant |<<prop-participants>>

|links |Id[Link] |Group, Event, Task, Location, Participant |<<prop-links>>, <<prop-locations>>, <<prop-participants>>

|locale |String |Group, Event, Task |<<prop-locale>>

|localizations |String [PatchObject] |Event, Task |<<prop-localizations>>

|locations |Id[Location] |Event, Task, Participant |<<prop-locations>>, <<prop-participants>>

|locationTypes |String[Boolean] |Location |<<prop-locations>>

|memberOf |Id[Boolean] |Participant |<<prop-participants>>

|method |String |Event, Task |<<prop-method>>

|name |String |Location, Conference, Participant |<<prop-locations>>, <<prop-conferences>>, <<prop-participants>>

|names |String[Boolean] |TimeZoneRule |<<prop-timeZones>>

|nthOfPeriod |Int |NDay |<<prop-recurrenceRules>>

|offset |SignedDuration |OffsetTrigger |<<prop-alerts>>

|offsetFrom |UTCDateTime |TimeZoneRule |<<prop-timeZones>>

|offsetTo |UTCDateTime |TimeZoneRule |<<prop-timeZones>>

|participants |Id[Participant] |Event, Task |<<prop-participants>>

|participation Comment |String |Participant |<<prop-participants>>

|participationStatus |String |Participant |<<prop-participants>>

|percentComplete |UnsignedInt |Task, Participant |<<prop-percentComplete>>

|priority |Int |Event, Task |<<prop-priority>>

|privacy |String |Event, Task |<<prop-privacy>>

|prodId |String |Event, Task, Group |<<prop-prodId>>

|progress |String |Task, Participant |<<prop-progress>>

|progressUpdated |UTCDateTime |Task, Participant |<<prop-progressUpdated>>

|recurrenceId |LocalDateTime |Event, Task |<<prop-recurrenceId>>

|recurrenceIdTimeZone |TimeZoneId\|null |Event, Task |<<prop-recurrenceIdTimeZone>>

|recurrenceOverrides |LocalDateTime [PatchObject] |Event, Task, TimeZoneRule |<<prop-recurrenceOverrides>>, <<prop-timeZones>>

|recurrenceRules |RecurrenceRule[] |Event, Task, TimeZoneRule |<<prop-recurrenceRules>>, <<prop-timeZones>>

|rel |String |Link |<<type-Link>>

|relatedTo |String[Relation] |Event, Task, Alert |<<prop-relatedTo>>, <<prop-alerts>>

|relation |String[Boolean] |Relation |<<type-Relation>>

|relativeTo |String |OffsetTrigger, Location |<<prop-alerts>>, <<prop-locations>>

|replyTo |String[String] |Event, Task |<<prop-replyTo>>

|replyToScheduleAgent |String |Event, Task |<<prop-replytoscheduleagent>>

|replyToScheduleForceSend |Boolean |Event, Task |<<prop-replytoscheduleforcesend>>

|replyToScheduleStatus |String[] |Event, Task |<<prop-replytoschedulestatus>>

|requestStatus |String |Event, Task |<<prop-requestStatus>>

|roles |String[Boolean] |Participant |<<prop-participants>>

|rscale |String |RecurrenceRule |<<prop-recurrenceRules>>

|sentFrom |String |Event, Task, Participant |<<prop-sentFrom>>, <<prop-participants>>

|standard |TimeZoneRule[] |TimeZone |<<prop-timeZones>>

|start |LocalDateTime |TimeZoneRule |<<prop-timeZones>>

|scheduleAgent |String |Participant |<<prop-participants>>

|scheduleForceSend |Boolean |Participant |<<prop-participants>>

|scheduleSequence |UnsignedInt |Participant |<<prop-participants>>

|scheduleStatus |String[] |Participant |<<prop-participants>>

|scheduleUpdated |UTCDateTime |Participant |<<prop-participants>>

|sendTo |String[String] |Participant |<<prop-participants>>

|sequence |UnsignedInt |Event, Task |<<prop-sequence>>

|showWithoutTime |Boolean |Event, Task |<<prop-showWithoutTime>>

|size |UnsignedInt |Link |<<type-Link>>

|skip |String |RecurrenceRule |<<prop-recurrenceRules>>

|source |String |Group |<<prop-source>>

|start |LocalDateTime |Event, Task |<<prop-start-jsevent>>, <<prop-start-jstask>>

|status |String |Event |<<prop-status-jsevent>>

|timeZone |TimeZoneId\|null |Event, Task, Location |<<prop-timeZone>>, <<prop-locations>>

|timeZones |TimeZoneId [TimeZone] |Group |<<prop-timeZones>>

|title |String |Event, Task, Group, Link |<<prop-title>>

|trigger |OffsetTrigger\| AbsoluteTrigger\| UnknownTrigger |Alert |<<prop-alerts>>

|tzId |String |TimeZone |<<prop-timeZones>>

|uid |String |Event, Task, Group, Alert, Location |<<prop-uid>>

|until |LocalDateTime |RecurrenceRule |<<prop-recurrenceRules>>

|updated |UTCDateTime |Event, Task, Group |<<prop-updated>>

|uri |String |Conference |<<prop-conferences>>

|url |String |TimeZone |<<prop-timeZones>>

|useDefaultAlerts |Boolean |Event, Task |<<useDefaultAlerts>>

|validUntil |UTCDateTime |TimeZone |<<prop-timeZones>>

|when |UTCDateTime |AbsoluteTrigger |<<prop-alerts>>
|===

[[iana-type-registry]]
==== Changes to the "JSCalendar Types" Registry

When <<RFC8984>> was published, IANA has created the "JSCalendar Types" registry
to avoid name collisions and provide a complete reference for all data types
used for JSCalendar property values. As this RFC document obsoletes <<RFC8984>>
the IANA registry contents shall be completely replaced with the following
definitions.

The registration process is the same as for the "JSCalendar Properties"
registry, as defined in <<iana-property-registry>>.

[[iana-type-registry-template]]
==== "JSCalendar Types" Registry Template

Type Name:: the name of the type

Reference or Description:: a brief description or RFC number and section
reference where the Type is specified (may be omitted for "reserved" type names)

Intended Use:: common, reserved, or obsolete

Change Controller:: who may request a change to this entry's definition (`IETF`
for RFCs from the IETF stream)

[[iana-type-registry-contents]]
=== Initial Contents for the "JSCalendar Types" Registry

The following table lists the initial entries of the JSCalendar Types registry.
All properties are for common use. All RFC section references are for this
document. The change controller for all these properties is "IETF".

[cols=2,options=header]
.Initial Contents for the "JSCalendar Types" Registry
|===
| Type Name | Reference or Description

|Alert
|<<prop-alerts>>

|Boolean
|<<type-signatures>>

|Duration
|<<type-Duration>>

|Id
|<<type-Id>>

|Int
|<<type-Int>>

|LocalDateTime
|<<type-LocalDateTime>>

|Link
|<<type-Link>>

|Location
|<<prop-locations>>

|NDay
|<<prop-recurrenceRules>>

|Number
|<<type-signatures>>

|Participant
|<<prop-participants>>

|PatchObject
|<<type-PatchObject>>

|RecurrenceRule
|<<prop-recurrenceRules>>

|Relation
|<<type-Relation>>

|SignedDuration
|<<type-SignedDuration>>

|String
|<<type-signatures>>

|TimeZone
|<<prop-timeZones>>

|TimeZoneId
|<<type-timeZoneId>>

|TimeZoneRule
|<<prop-timeZones>>

|UnsignedInt
|<<type-UnsignedInt>>

|UTCDateTime
|<<type-UTCDateTime>>

|Conference
|<<prop-conferences>>
|===

[[iana-enum-registry]]
=== Changes to the "JSCalendar Enum Values" Registry

When <<RFC8984>> was published, IANA has created the "JSCalendar Enum Values"
registry to allow interoperable extension of semantics for properties with
enumerable values. As this RFC document obsoletes <<RFC8984>> the IANA registry
contents shall be completely replaced with the following definitions.

Each property with enum values has a subregistry of allowed values. The
registration process for a new enum value or adding a new enumerable property is
the same as for the "JSCalendar Properties" registry, as defined in
<<iana-property-registry>>.

[[iana-enum-registry-registry-template]]
==== "JSCalendar Enum Values" Registry Property Template

This template is for adding a subregistry for a new enumerable property to the
"JSCalendar Enum" registry.

Property Name:: These are the name(s) of the property or properties where these
values may be used. This *MUST* be registered in the "JSCalendar Properties"
registry.

Context:: This is the list of allowed object types where the property or
properties may appear, as registered in the "JSCalendar Properties" registry.
This disambiguates where there may be two distinct properties with the same name
in different contexts.

Change Controller:: (`IETF` for properties defined in RFCs from the IETF
stream).

Initial Contents:: This is the initial list of defined values for this enum,
using the template defined in <<iana-enum-registry-value-template>>. A
subregistry will be created with these values for this property name/context
tuple.

[[iana-enum-registry-value-template]]
==== "JSCalendar Enum Values" Registry Value Template

This template is for adding a new enum value to a subregistry in the JSCalendar
Enum registry.

Enum Value:: the verbatim value of the enum

Reference or Description:: a brief description or RFC number and section
reference for the semantics of this value

[[iana-enum-registry-contents]]
==== Initial Contents for the "JSCalendar Enum Values" registry

For each subregistry created in this section, all RFC section references are for
this document.

Property Name:: action
Context:: Alert
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for action (Context: Alert)
|===
| Enum Value | Reference or Description

| display | <<prop-alerts>>
| email | <<prop-alerts>>
|===

Property Name:: display
Context:: Link
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for display (Context: Link)
|===
| Enum Value | Reference or Description

| badge | <<type-Link>>
| graphic | <<type-Link>>
| fullsize | <<type-Link>>
| thumbnail | <<type-Link>>
|===

Property Name:: features
Context:: VirtualLocation
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for features (Context: Conference)
|===
| Enum Value | Reference or Description

| audio | <<prop-conferences>>
| chat | <<prop-conferences>>
| feed | <<prop-conferences>>
| moderator | <<prop-conferences>>
| phone | <<prop-conferences>>
| screen | <<prop-conferences>>
| video | <<prop-conferences>>
|===

Property Name:: freeBusyStatus
Context:: Event, Task
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for freeBusyStatus (Context: Event, Task)
|===
| Enum Value | Reference or Description

| free | <<prop-freeBusyStatus>>
| busy | <<prop-freeBusyStatus>>
|===

Property Name:: kind
Context:: Participant
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for kind (Context: Participant)
|===
| Enum Value | Reference or Description

| individual | <<prop-participants>>
| group | <<prop-participants>>
| resource | <<prop-participants>>
| location | <<prop-participants>>
|===

Property Name:: participationStatus
Context:: Participant
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for participationStatus (Context: Participant)
|===
| Enum Value | Reference or Description

| needs-action | <<prop-participants>>
| accepted | <<prop-participants>>
| declined | <<prop-participants>>
| tentative | <<prop-participants>>
| delegated | <<prop-participants>>
|===

Property Name:: privacy
Context:: Event, Task
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for privacy (Context: Event, Task)
|===
| Enum Value | Reference or Description

| public | <<prop-privacy>>
| private | <<prop-privacy>>
| secret | <<prop-privacy>>
|===

Property Name:: progress
Context:: Task, Participant
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for progress (Context: Task, Participant)
|===
| Enum Value | Reference or Description

| needs-action | <<prop-progress>>
| in-process | <<prop-progress>>
| completed | <<prop-progress>>
| failed | <<prop-progress>>
| cancelled | <<prop-progress>>
|===

Property Name:: relation
Context:: Relation
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for relation (Context: Relation)
|===
| Enum Value | Reference or Description

| first | <<type-Relation>>
| next | <<type-Relation>>
| child | <<type-Relation>>
| parent | <<type-Relation>>
|===

Property Name:: relativeTo
Context:: OffsetTrigger, Location
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for relativeTo (Context: OffsetTrigger, Location)
|===
| Enum Value | Reference or Description

| start | <<prop-alerts>>
| end | <<prop-alerts>>
|===

Property Name:: roles
Context:: Participant
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for roles (Context: Participant)
|===
| Enum Value | Reference or Description

| owner | <<prop-participants>>
| attendee | <<prop-participants>>
| optional | <<prop-participants>>
| informational | <<prop-participants>>
| chair | <<prop-participants>>
| contact | <<prop-participants>>
|===

Property Name:: scheduleAgent
Context:: Participant
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for replyToScheduleAgent (Context: Event, Task) and scheduleAgent (Context: Participant)
|===
| Enum Value | Reference or Description

| server | <<prop-participants>>
| client | <<prop-participants>>
| none | <<prop-participants>>
|===

Property Name:: status
Context:: Event
Change Controller:: IETF
Initial Contents::
+
[options=header,cols=2]
.JSCalendar Enum Values for status (Context: Event)
|===
| Enum Value | Reference or Description

| confirmed | <<prop-status-jsevent>>
| cancelled | <<prop-status-jsevent>>
| tentative | <<prop-status-jsevent>>
|===
